### ISSUE TITLE
saya pintar

### ISSUE THREAD

**Issue by wildan-a** [FaruuZa/pre-ujiSkema#1]
$table->id();
            $table->foreignId('suplier_id');
            $table->string("name");
            $table->string("fulladdress");
            $table->string("street");
            $table->string("municipality");
            $table->string("categories");
            $table->string("amenities")->nullable();
            $table->string("phone");
            $table->enum("status", ["YES","NO"])->default('NO');
            $table->integer("review_count");
            $table->string("average_rating");
            $table->string("review_url");
            $table->string("google_maps_url");
            $table->string("latitude");
            $table->string("longitude");
            $table->string("website")->nullable();
            $table->string("domain")->nullable();
            $table->string("open_hours");
            $table->string("featured_image");
            $table->string("cid");
            $table->string("place_id");
            $table->timestamps();

**Comment by FaruuZa** [comment]
yak terimakasih
